"use client";

import React, { useState } from 'react';
import { Terminal, Download, Copy, Check } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { CodeBlock } from '@/components/ui/CodeBlock';

export interface InstallScriptProps {
    targetIp?: string;
    managerIp?: string;
    agentName?: string;
    className?: string;
}

export function InstallScript({
    targetIp = '',
    managerIp = '192.168.1.206',
    agentName,
    className
}: InstallScriptProps) {
    const [platform, setPlatform] = useState<'linux' | 'windows'>('linux');
    const [customName, setCustomName] = useState(agentName || '');
    const [copied, setCopied] = useState(false);

    const agentNameValue = customName || targetIp || 'agent-001';

    const linuxScript = `#!/bin/bash
# Wazuh Agent Installation Script for ${targetIp || 'target'}
# Generated by SOC Dashboard

set -e

echo "=== Installing Wazuh Agent ==="

# Download and install
curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --dearmor | sudo tee /etc/apt/keyrings/wazuh.gpg > /dev/null
echo "deb [signed-by=/etc/apt/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | sudo tee /etc/apt/sources.list.d/wazuh.list

sudo apt-get update && sudo apt-get install -y wazuh-agent

# Configure
sudo sed -i 's/MANAGER_IP/${managerIp}/' /var/ossec/etc/ossec.conf
echo "${agentNameValue}" | sudo tee /var/ossec/etc/client.keys

# Start
sudo systemctl daemon-reload
sudo systemctl enable wazuh-agent
sudo systemctl start wazuh-agent

echo "=== Installation Complete ==="
sudo systemctl status wazuh-agent`;

    const windowsScript = `# PowerShell Script for Wazuh Agent Installation
# Run as Administrator

$ManagerIP = "${managerIp}"
$AgentName = "${agentNameValue}"

Write-Host "=== Installing Wazuh Agent ===" -ForegroundColor Green

# Download installer
$InstallerUrl = "https://packages.wazuh.com/4.x/windows/wazuh-agent-4.7.0-1.msi"
$InstallerPath = "$env:TEMP\\wazuh-agent.msi"

Invoke-WebRequest -Uri $InstallerUrl -OutFile $InstallerPath

# Install with parameters
msiexec.exe /i $InstallerPath /q WAZUH_MANAGER=$ManagerIP WAZUH_AGENT_NAME=$AgentName

# Start service
Start-Sleep -Seconds 5
Start-Service WazuhSvc

Write-Host "=== Installation Complete ===" -ForegroundColor Green
Get-Service WazuhSvc`;

    const script = platform === 'linux' ? linuxScript : windowsScript;

    const handleDownload = () => {
        const blob = new Blob([script], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = platform === 'linux' ? 'install-wazuh-agent.sh' : 'install-wazuh-agent.ps1';
        a.click();
        URL.revokeObjectURL(url);
    };

    const handleCopy = async () => {
        await navigator.clipboard.writeText(script);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className={className}>
            <div className="flex items-center gap-2 mb-4">
                <Terminal className="w-5 h-5 text-purple-400" />
                <span className="font-semibold text-slate-200">Agent Install Script</span>
            </div>

            <div className="flex flex-wrap gap-4 mb-4">
                <div className="flex gap-2">
                    <button
                        onClick={() => setPlatform('linux')}
                        className={`px-4 py-2 rounded-lg text-sm ${platform === 'linux'
                                ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-400'
                                : 'bg-slate-800 border-slate-700 text-slate-400'
                            } border`}
                    >
                        Linux
                    </button>
                    <button
                        onClick={() => setPlatform('windows')}
                        className={`px-4 py-2 rounded-lg text-sm ${platform === 'windows'
                                ? 'bg-blue-500/20 border-blue-500/50 text-blue-400'
                                : 'bg-slate-800 border-slate-700 text-slate-400'
                            } border`}
                    >
                        Windows
                    </button>
                </div>

                <input
                    type="text"
                    value={customName}
                    onChange={(e) => setCustomName(e.target.value)}
                    placeholder="Agent name (optional)"
                    className="px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg text-slate-200 text-sm"
                />
            </div>

            <div className="relative">
                <CodeBlock code={script} />

                <div className="absolute top-2 right-2 flex gap-2">
                    <button
                        onClick={handleCopy}
                        className={`p-2 rounded ${copied ? 'bg-emerald-500/20 text-emerald-400' : 'bg-slate-800 text-slate-400 hover:bg-slate-700'}`}
                    >
                        {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                    </button>
                    <button
                        onClick={handleDownload}
                        className="p-2 rounded bg-slate-800 text-slate-400 hover:bg-slate-700"
                    >
                        <Download className="w-4 h-4" />
                    </button>
                </div>
            </div>
        </div>
    );
}
